FROM karrio/dashboard:2024.12.6

# Use the official environment variables from Karrio documentation
# https://www.karrio.io/docs/self-hosting/environment
# Note: These are overridden by Render environment variables
ENV KARRIO_PUBLIC_URL=http://localhost:5002
ENV DASHBOARD_URL=http://localhost:3000
