services:
  - type: web
    name: karrio-api
    runtime: docker
    plan: starter
    region: oregon
    healthCheckPath: /
    startCommand: >
     sh -lc "karrio migrate &&
              karrio collectstatic --noinput || true &&
              karrio start"
    dockerfilePath: Dockerfile
    envVars:
      - key: KARRIO_HTTP_PORT
        value: "$PORT"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG_MODE
        value: "False"
      - key: USE_HTTPS
        value: "True"
      - key: KARRIO_PUBLIC_URL
        value: https://karrio-api.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://karrio-dashboard.onrender.com,https://app.reboundjerseys.com
      - key: ALLOWED_HOSTS
        value: karrio-api.onrender.com

      # Supabase Postgres
      - key: DATABASE_ENGINE
        value: postgresql_psycopg2
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_NAME
        sync: false

      # Redis / Key Value
      - key: REDIS_HOST
        fromService:
          type: keyvalue
          name: rebound-karrio-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: keyvalue
          name: rebound-karrio-redis
          property: port

      # Worker config
      - key: DETACHED_WORKER
        value: "False"
      - key: KARRIO_WORKERS
        value: "2"
      - key: BACKGROUND_WORKERS
        value: "2"

      # Bootstrap admin
      - key: ADMIN_EMAIL
        value: admin@reboundjerseys.com
      - key: ADMIN_PASSWORD
        generateValue: true

  - type: worker
    name: karrio-worker
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: SECRET_KEY
        fromService:
          name: karrio-api
          type: web
          envVarKey: SECRET_KEY
      - key: DEBUG_MODE
        value: "False"
      - key: USE_HTTPS
        value: "True"

      # Supabase Postgres
      - key: DATABASE_ENGINE
        value: postgresql_psycopg2
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        value: "5432"
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_NAME
        sync: false

      # Redis / Key Value
      - key: REDIS_HOST
        fromService:
          type: keyvalue
          name: rebound-karrio-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: keyvalue
          name: rebound-karrio-redis
          property: port

      # Worker config
      - key: DETACHED_WORKER
        value: "False"
      - key: KARRIO_WORKERS
        value: "2"
      - key: BACKGROUND_WORKERS
        value: "2"

  - type: web
    name: karrio-dashboard
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile.dashboard
    envVars:
      - key: DASHBOARD_PORT
        value: "$PORT"
      - key: NEXT_PUBLIC_DASHBOARD_URL
        value: https://karrio-dashboard.onrender.com
      - key: DASHBOARD_URL
        value: https://karrio-dashboard.onrender.com
      - key: NEXTAUTH_URL
        value: https://karrio-dashboard.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        fromService:
          name: karrio-dashboard
          type: web
          envVarKey: JWT_SECRET
      - key: NEXT_PUBLIC_KARRIO_API_URL
        value: https://karrio-api.onrender.com

  - type: keyvalue
    name: rebound-karrio-redis
    plan: free
    ipAllowList: []